/*
 * JHide Copyright (C) 2010 Mladen Krstic <mkrstich@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <http://www.gnu.org/licenses/>.
 */

package jhide;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Point;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import jhide.misc.Utils;

/**
 *
 * @author Mladen
 */
public class AboutDialog extends javax.swing.JDialog {

    private MainFrame parent;
    /** Creates new form AboutDialog */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = (MainFrame) parent;
        initComponents();
        textLanguageUpdate();
        Point p = Utils.getScreenCenterCoords(this);
        this.setLocation(p);
    }
    private void textLanguageUpdate() {
        aboutDescLabel.setText(parent.bundle.getString("AboutDesc"));
        aboutVersionLabel.setText(parent.bundle.getString("AboutVersion"));
        aboutAuthorLabel.setText(parent.bundle.getString("AboutAuthor"));
        aboutAuthorValueLabel.setText(parent.bundle.getString("AboutAuthorValue"));
        aboutContactLabel.setText(parent.bundle.getString("AboutContact"));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        aboutDescLabel = new javax.swing.JLabel();
        aboutVersionLabel = new javax.swing.JLabel();
        aboutAuthorLabel = new javax.swing.JLabel();
        aboutContactLabel = new javax.swing.JLabel();
        aboutVersionNumberLabel = new javax.swing.JLabel();
        aboutAuthorValueLabel = new javax.swing.JLabel();
        aboutContactValueLabel = new javax.swing.JLabel();
        aboutLicenceButton = new javax.swing.JButton();
        aboutCloseButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jhide/resources/topsecret128x128.png"))); // NOI18N
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 36));
        jLabel2.setText("JHide!");

        aboutDescLabel.setText("Steganography tool to present basic usage...");

        aboutVersionLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        aboutVersionLabel.setText("Version:");

        aboutAuthorLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        aboutAuthorLabel.setText("Author:");

        aboutContactLabel.setFont(new java.awt.Font("Tahoma", 1, 11));
        aboutContactLabel.setText("Contact:");

        aboutVersionNumberLabel.setText("1.0.0");

        aboutAuthorValueLabel.setText("Mladen Krstic");

        aboutContactValueLabel.setForeground(java.awt.Color.blue);
        aboutContactValueLabel.setText("mkrstich@gmail.com");
        aboutContactValueLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutContactValueLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutContactValueLabelMouseClicked(evt);
            }
        });

        aboutLicenceButton.setText("Licence");
        aboutLicenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutLicenceButtonActionPerformed(evt);
            }
        });

        aboutCloseButton.setText("Close");
        aboutCloseButton.setPreferredSize(new java.awt.Dimension(69, 23));
        aboutCloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aboutCloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(aboutDescLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(aboutLicenceButton)
                        .addGap(18, 18, 18)
                        .addComponent(aboutCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aboutVersionLabel)
                            .addComponent(aboutAuthorLabel)
                            .addComponent(aboutContactLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aboutContactValueLabel)
                            .addComponent(aboutAuthorValueLabel)
                            .addComponent(aboutVersionNumberLabel))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(aboutDescLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aboutVersionLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aboutAuthorLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aboutContactLabel))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(aboutVersionNumberLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aboutAuthorValueLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(aboutContactValueLabel)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aboutLicenceButton)
                            .addComponent(aboutCloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aboutCloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutCloseButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_aboutCloseButtonActionPerformed

    private void aboutLicenceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aboutLicenceButtonActionPerformed
        LicenceDialog ld = new LicenceDialog(parent, true);
        ld.setVisible(true);
    }//GEN-LAST:event_aboutLicenceButtonActionPerformed

    private void aboutContactValueLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutContactValueLabelMouseClicked
        if (Desktop.isDesktopSupported()) {
            Desktop desktop = Desktop.getDesktop();
            if (desktop.isSupported(Desktop.Action.MAIL)) {
                String mailTo = aboutContactValueLabel.getText() + "?subject=JHide%20feedback";
                URI uri = null;
                try {
                    uri = new URI("mailto", mailTo, null);
                    desktop.mail();
                    aboutContactValueLabel.setForeground(Color.magenta);
                } catch (IOException ioe) {
                    ioe.printStackTrace();
                } catch (URISyntaxException use) {
                    use.printStackTrace();
                }
            }
        }
    }//GEN-LAST:event_aboutContactValueLabelMouseClicked

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AboutDialog dialog = new AboutDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutAuthorLabel;
    private javax.swing.JLabel aboutAuthorValueLabel;
    private javax.swing.JButton aboutCloseButton;
    private javax.swing.JLabel aboutContactLabel;
    private javax.swing.JLabel aboutContactValueLabel;
    private javax.swing.JLabel aboutDescLabel;
    private javax.swing.JButton aboutLicenceButton;
    private javax.swing.JLabel aboutVersionLabel;
    private javax.swing.JLabel aboutVersionNumberLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

}
